surveyApp/config/routes.rb
SurveyApp::Application.routes.draw do
  resources :surveys

  get "survey_app_home/index"

  

end

surveyApp/app/models/survey.rb
class Survey < ActiveRecord::Base
end

surveyApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

surveyApp/app/controllers/survey_app_home_controller.rb
class SurveyAppHomeController < ApplicationController
  def index
  end
end

surveyApp/app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def new
  end

  def create
  end

  def delete
  end

  def view
  end

  def index
  end
end

surveyApp/app/helpers/application_helper.rb
module ApplicationHelper
end

surveyApp/app/helpers/survey_app_home_helper.rb
module SurveyAppHomeHelper
end

surveyApp/app/helpers/surveys_helper.rb
module SurveysHelper
end

surveyApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SurveyApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

surveyApp/app/views/survey_app_home/index.html.erb
<h1>SurveyAppHome#index</h1>
<p>Find me in app/views/survey_app_home/index.html.erb</p>
<%= link_to "New Survey", new_survey_path %>

surveyApp/app/views/surveys/create.html.erb
<h1>Survey#create</h1>
<p>Find me in app/views/survey/create.html.erb</p>

surveyApp/app/views/surveys/delete.html.erb
<h1>Survey#delete</h1>
<p>Find me in app/views/survey/delete.html.erb</p>

surveyApp/app/views/surveys/index.html.erb
<h1>Survey#index</h1>
<p>Find me in app/views/survey/index.html.erb</p>

surveyApp/app/views/surveys/new.html.erb
<h1>Survey#new</h1>
<p>Find me in app/views/survey/new.html.erb</p>

surveyApp/app/views/surveys/view.html.erb
<h1>Survey#view</h1>
<p>Find me in app/views/survey/view.html.erb</p>